In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

In [2]:
# Sentences
sent = ['the glass of milk', 
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your vidoes are good']

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your vidoes are good']

In [18]:
# Define the vocabulary size
voc_size = 10000

In [19]:
## one hot representation
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[329, 5156, 6769, 9080],
 [329, 5156, 6769, 5690],
 [329, 2652, 6769, 1839],
 [3337, 3058, 3240, 7090, 4281],
 [3337, 3058, 3240, 7090, 7401],
 [7163, 329, 977, 6769, 7274],
 [4332, 1094, 8303, 7090]]

In [20]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [32]:
sent_length = 8

embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  329 5156 6769 9080]
 [   0    0    0    0  329 5156 6769 5690]
 [   0    0    0    0  329 2652 6769 1839]
 [   0    0    0 3337 3058 3240 7090 4281]
 [   0    0    0 3337 3058 3240 7090 7401]
 [   0    0    0 7163  329  977 6769 7274]
 [   0    0    0    0 4332 1094 8303 7090]]


In [22]:
## feature representation
dim=10 # 300 in word2vec

model=Sequential()

model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[[ 0.02224603, -0.04283254,  0.02210976,  0.01841195,
          0.02414748,  0.03468915,  0.04443381,  0.04429681,
         -0.00519741, -0.0366176 ],
        [ 0.02224603, -0.04283254,  0.02210976,  0.01841195,
          0.02414748,  0.03468915,  0.04443381,  0.04429681,
         -0.00519741, -0.0366176 ],
        [ 0.02224603, -0.04283254,  0.02210976,  0.01841195,
          0.02414748,  0.03468915,  0.04443381,  0.04429681,
         -0.00519741, -0.0366176 ],
        [ 0.02224603, -0.04283254,  0.02210976,  0.01841195,
          0.02414748,  0.03468915,  0.04443381,  0.04429681,
         -0.00519741, -0.0366176 ],
        [ 0.024153  ,  0.00649941, -0.04089892, -0.03037781,
         -0.00591844, -0.00299792, -0.0324742 , -0.04675162,
         -0.02520262, -0.0214906 ],
        [-0.02191166, -0.01025081,  0.02387111, -0.01653238,
         -0.0049854 ,  0.00214656,  0.02421496,  0.00110527,
         -0.04715437,  0.00680159],
        [ 0.00358467,  0.03891274,  0.0055756 ,  0.0

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0,  329, 5156, 6769, 9080])

In [37]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[ 0.02224603, -0.04283254,  0.02210976,  0.01841195,  0.02414748,
         0.03468915,  0.04443381,  0.04429681, -0.00519741, -0.0366176 ],
       [ 0.02224603, -0.04283254,  0.02210976,  0.01841195,  0.02414748,
         0.03468915,  0.04443381,  0.04429681, -0.00519741, -0.0366176 ],
       [ 0.02224603, -0.04283254,  0.02210976,  0.01841195,  0.02414748,
         0.03468915,  0.04443381,  0.04429681, -0.00519741, -0.0366176 ],
       [ 0.02224603, -0.04283254,  0.02210976,  0.01841195,  0.02414748,
         0.03468915,  0.04443381,  0.04429681, -0.00519741, -0.0366176 ],
       [ 0.024153  ,  0.00649941, -0.04089892, -0.03037781, -0.00591844,
        -0.00299792, -0.0324742 , -0.04675162, -0.02520262, -0.0214906 ],
       [-0.02191166, -0.01025081,  0.02387111, -0.01653238, -0.0049854 ,
         0.00214656,  0.02421496,  0.00110527, -0.04715437,  0.00680159],
       [ 0.00358467,  0.03891274,  0.0055756 ,  0.04113681, -0.00082479,
         0.01973145, -0.01497742,  0.03098079